spring.application.name=baskapp-social

spring.config.import=optional:file:.env[.properties]

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# STACK TRACE
server.error.include-stacktrace=never

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.algorithm=${JWT_ALGORITHM}

internal.token=${INTERNAL_TOKEN}

